import Foundation

/// Generates markdown protocol documentation from a ProtocolMap and
/// observed GATT structure — the deliverable of a reverse-engineering session.
public enum ProtocolDocGenerator {
    public struct GATTSummary: Sendable {
        public var serviceUUID: String
        public var characteristics: [(uuid: String, properties: String, lastValueHex: String?)]
        public init(serviceUUID: String,
                    characteristics: [(uuid: String, properties: String, lastValueHex: String?)]) {
            self.serviceUUID = serviceUUID
            self.characteristics = characteristics
        }
    }

    public static func markdown(map: ProtocolMap,
                                gatt: [GATTSummary] = [],
                                observedNotifications: [(timestamp: Date, hex: String)] = []) -> String {
        let df = ISO8601DateFormatter()
        var md = """
        # \(map.deviceModel) — BLE Protocol Documentation

        Generated by TP25 Studio on \(df.string(from: Date())).

        > ⚠️ This protocol was reverse-engineered empirically. Entries below were
        > visually confirmed on real hardware; everything else is unverified.

        """

        if !map.deviceNamePrefixes.isEmpty {
            md += "\n**Advertised name prefixes:** " + map.deviceNamePrefixes.map { "`\($0)`" }.joined(separator: ", ") + "\n"
        }
        md += "\n**CCT range:** \(map.cctRange.lowerBound)K – \(map.cctRange.upperBound)K (assumed until swept)\n"

        if !gatt.isEmpty {
            md += "\n## GATT Structure\n"
            for service in gatt {
                md += "\n### Service `\(service.serviceUUID)`\n\n"
                md += "| Characteristic | Properties | Last value |\n|---|---|---|\n"
                for ch in service.characteristics {
                    md += "| `\(ch.uuid)` | \(ch.properties) | \(ch.lastValueHex.map { "`\($0)`" } ?? "—") |\n"
                }
            }
        }

        md += "\n## Confirmed Commands\n"
        if map.entries.isEmpty {
            md += "\n_No commands confirmed yet. Run the Discovery Assistant._\n"
        }
        for entry in map.entries.sorted(by: { $0.kind.rawValue < $1.kind.rawValue }) {
            md += "\n### \(entry.kind.rawValue.uppercased())\n\n"
            md += "- **Characteristic:** `\(entry.characteristicUUID)` (service `\(entry.serviceUUID)`)\n"
            md += "- **Encoding family:** \(entry.family.displayName)\n"
            if let t = entry.template {
                md += "- **Packet template:** `\(Data(t.base).hexString)`\n"
                md += "- **Parameter byte offsets:** \(t.parameterOffsets.map(String.init).joined(separator: ", "))\n"
                if let cs = t.checksum, cs != CommandTemplate.ChecksumRule.none {
                    md += "- **Checksum:** \(cs.rawValue)\n"
                }
            }
            if !entry.exampleHex.isEmpty {
                md += "- **Example packet:** `\(entry.exampleHex)`\n"
            }
            md += "- **Confirmed:** \(df.string(from: entry.confirmedAt))\n"
            if !entry.notes.isEmpty { md += "- **Notes:** \(entry.notes)\n" }
        }

        if !observedNotifications.isEmpty {
            md += "\n## Observed Notifications\n\n| Timestamp | Payload |\n|---|---|\n"
            for n in observedNotifications.suffix(50) {
                md += "| \(df.string(from: n.timestamp)) | `\(n.hex)` |\n"
            }
        }
        return md
    }
}
